#!/bin/sh
sed -ri '/check_signature/s@^[^#]@#&@' /etc/opkg.conf

# 设置所有网口可访问网页终端
uci delete ttyd.@ttyd[0].interface
# 设置所有网口可连接 SSH
uci set dropbear.@dropbear[0].Interface=''

uci set network.lan.netmask='255.255.0.0'


uci set wireless.default_radio0.ssid=OpenWrt-$(cat /sys/class/ieee80211/phy0/macaddress|awk -F ":" '{print $5""$6 }' | tr 'a-z' 'A-Z')-2.4G
uci set wireless.default_radio1.ssid=OpenWrt-$(cat /sys/class/ieee80211/phy0/macaddress|awk -F ":" '{print $5""$6 }' | tr 'a-z' 'A-Z')-5G
#uci set wireless.default_radio0.ssid=TIKTOK
uci set wireless.default_radio0.encryption=psk2+ccmp
uci set wireless.default_radio1.encryption=psk2+ccmp
uci set wireless.default_radio0.key=2137819@vodip.cn
uci set wireless.default_radio1.key=2137819@vodip.cn
uci commit wireless


uci commit

sed -i 's/root::0:0:99999:7:::/root:$1$Ir.krpSQ$EBAHFrS1bSmqtgvacpPzR1:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$Ir.krpSQ$EBAHFrS1bSmqtgvacpPzR1:0:0:99999:7:::/g' /etc/shadow
echo > /etc/opkg/distfeeds.conf
sed -i '$a src/gz openwrt_kmods http://s2.vodip.cn:30000/c%3a/releases/21.02.7/targets/ramips/mt7621/kmods/5.4.238-1-9075b32d59737ae13839f94851acafe75' /etc/opkg/distfeeds.conf
sed -i '$a src/gz openwrt_core http://s2.vodip.cn:30000/c%3a/releases/21.02.7/targets/ramips/mt7621/packages' /etc/opkg/distfeeds.conf
sed -i '$a src/gz openwrt_base http://s2.vodip.cn:30000/c%3a/releases/21.02.3/packages/mipsel_24kc/base' /etc/opkg/distfeeds.conf
sed -i '$a src/gz openwrt_luci http://s2.vodip.cn:30000/c%3a/releases/21.02.3/packages/mipsel_24kc/luci' /etc/opkg/distfeeds.conf
sed -i '$a src/gz openwrt_packages http://s2.vodip.cn:30000/c%3a/releases/21.02.3/packages/mipsel_24kc/packages' /etc/opkg/distfeeds.conf
sed -i '$a src/gz openwrt_routing http://s2.vodip.cn:30000/c%3a/releases/21.02.3/packages/mipsel_24kc/routing' /etc/opkg/distfeeds.conf
sed -i '$a src/gz openwrt_telephony http://s2.vodip.cn:30000/c%3a/releases/21.02.3/packages/mipsel_24kc/telephony' /etc/opkg/distfeeds.conf

#sysupgrade --restore-backup /etc/8929-20251117-2137819@vodip.cn.tar.gz
tar -xzvf /etc/8929-20251117-2137819@vodip.cn.tar.gz -C /
#/etc/init.d/system restart
/etc/init.d/network restart

exit 0
