name: r6220-padavan

on: 
  workflow_dispatch:


jobs:
  Build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
    - name: Clone source code
      run: |
        git clone --depth=1 https://e.coding.net/hanwckf/rt-n56u/padavan.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: R6220
        CONFIG_FILE: config/r6220-padavan
      run: |
        mv $GITHUB_WORKSPACE/patch/padavan/default-Aimydee.h /opt/rt-n56u/trunk/user/shared/defaults.h
        mv $GITHUB_WORKSPACE/patch/padavan/www.zip /opt/rt-n56u/trunk/www.zip
        mv $CONFIG_FILE /opt/rt-n56u/trunk/configs/templates/$TNAME.config
        cd /opt/rt-n56u/trunk
        rm -rf user/www
        unzip www.zip -d user/www
        cp -f configs/templates/$TNAME.config .config
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: R6220-Padavan
        path: /opt/images
